# Generated by Django 3.2.8 on 2021-11-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('BX', '必修'), ('XX', '限选'), ('RX', '任选')], default='BX', max_length=2)),
                ('credit', models.IntegerField()),
                ('override_credit', models.IntegerField(default=-1)),
                ('score', models.CharField(max_length=3)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculator.student')),
            ],
        ),
    ]
