# Generated by Django 3.2.8 on 2021-11-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', '优秀'), ('B', '良好'), ('C', '中等'), ('D', '及格'), ('F', '不及格'), ('P', '通过')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='override_credit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
