# Generated by Django 3.2.8 on 2021-11-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20211115_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
