# Generated by Django 3.2.8 on 2021-11-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_course_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
